### ISSUE TITLE
clang++ compile error

### ISSUE THREAD

**Issue by ktprime** [hordi/hash#3]
clang++: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
In file included from \rank\ebench.cpp:90:
\rank/hrd/hash_set.h:837:55: error: 'hash_eql' is a protected member of 'hrd::hash_base'
class hash_set : public hash_base, private hash_base::hash_eql<Key, Hash, Pred>
                                                      ^
\rank/hrd/hash_set.h:121:9: note: declared protected here
        hash_eql : private Hasher, private KeyEql
        ^
\rank/hrd/hash_set.h:1038:55: error: 'hash_eql' is a protected member of 'hrd::hash_base'
class hash_map : public hash_base, private hash_base::hash_eql<Key, Hash, Pred>
                                                      ^

**Comment by hordi** [comment]
fixed
